# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tokoin-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RealmSwift'
  # Pods for Tokoin-Test

  target 'Tokoin-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tokoin-TestUITests' do
    # Pods for testing
  end

end
